version: '3.9'

volumes:
  pg_data:

services:
  postgres:
    image: postgres:15.1-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  postgres_test:
    image: postgres:15.1-alpine
    container_name: postgres_test
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "54321:5432"
