// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: proto/pair.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PairClient is the client API for Pair service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PairClient interface {
	GetAll(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (*GetAllResponse, error)
}

type pairClient struct {
	cc grpc.ClientConnInterface
}

func NewPairClient(cc grpc.ClientConnInterface) PairClient {
	return &pairClient{cc}
}

func (c *pairClient) GetAll(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (*GetAllResponse, error) {
	out := new(GetAllResponse)
	err := c.cc.Invoke(ctx, "/proto.Pair/GetAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PairServer is the server API for Pair service.
// All implementations must embed UnimplementedPairServer
// for forward compatibility
type PairServer interface {
	GetAll(context.Context, *GetAllRequest) (*GetAllResponse, error)
	mustEmbedUnimplementedPairServer()
}

// UnimplementedPairServer must be embedded to have forward compatible implementations.
type UnimplementedPairServer struct {
}

func (UnimplementedPairServer) GetAll(context.Context, *GetAllRequest) (*GetAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedPairServer) mustEmbedUnimplementedPairServer() {}

// UnsafePairServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PairServer will
// result in compilation errors.
type UnsafePairServer interface {
	mustEmbedUnimplementedPairServer()
}

func RegisterPairServer(s grpc.ServiceRegistrar, srv PairServer) {
	s.RegisterService(&Pair_ServiceDesc, srv)
}

func _Pair_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PairServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Pair/GetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PairServer).GetAll(ctx, req.(*GetAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Pair_ServiceDesc is the grpc.ServiceDesc for Pair service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Pair_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Pair",
	HandlerType: (*PairServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAll",
			Handler:    _Pair_GetAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/pair.proto",
}
