name: tests

on:
  push:
    branches:
      - master
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - run: go version

      - uses: actions/checkout@v3

      - name: Run tests
        run: go test ./...
