// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	entity "github.com/PaulYakow/gophkeeper/internal/entity"
	gomock "github.com/golang/mock/gomock"
)

// MockIAuthorizationService is a mock of IAuthorizationService interface.
type MockIAuthorizationService struct {
	ctrl     *gomock.Controller
	recorder *MockIAuthorizationServiceMockRecorder
}

// MockIAuthorizationServiceMockRecorder is the mock recorder for MockIAuthorizationService.
type MockIAuthorizationServiceMockRecorder struct {
	mock *MockIAuthorizationService
}

// NewMockIAuthorizationService creates a new mock instance.
func NewMockIAuthorizationService(ctrl *gomock.Controller) *MockIAuthorizationService {
	mock := &MockIAuthorizationService{ctrl: ctrl}
	mock.recorder = &MockIAuthorizationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAuthorizationService) EXPECT() *MockIAuthorizationServiceMockRecorder {
	return m.recorder
}

// LoginUser mocks base method.
func (m *MockIAuthorizationService) LoginUser(login, password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoginUser", login, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoginUser indicates an expected call of LoginUser.
func (mr *MockIAuthorizationServiceMockRecorder) LoginUser(login, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginUser", reflect.TypeOf((*MockIAuthorizationService)(nil).LoginUser), login, password)
}

// RegisterUser mocks base method.
func (m *MockIAuthorizationService) RegisterUser(login, password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterUser", login, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterUser indicates an expected call of RegisterUser.
func (mr *MockIAuthorizationServiceMockRecorder) RegisterUser(login, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterUser", reflect.TypeOf((*MockIAuthorizationService)(nil).RegisterUser), login, password)
}

// MockIAuthorizationRepo is a mock of IAuthorizationRepo interface.
type MockIAuthorizationRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIAuthorizationRepoMockRecorder
}

// MockIAuthorizationRepoMockRecorder is the mock recorder for MockIAuthorizationRepo.
type MockIAuthorizationRepoMockRecorder struct {
	mock *MockIAuthorizationRepo
}

// NewMockIAuthorizationRepo creates a new mock instance.
func NewMockIAuthorizationRepo(ctrl *gomock.Controller) *MockIAuthorizationRepo {
	mock := &MockIAuthorizationRepo{ctrl: ctrl}
	mock.recorder = &MockIAuthorizationRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAuthorizationRepo) EXPECT() *MockIAuthorizationRepoMockRecorder {
	return m.recorder
}

// CloseConnection mocks base method.
func (m *MockIAuthorizationRepo) CloseConnection() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseConnection")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseConnection indicates an expected call of CloseConnection.
func (mr *MockIAuthorizationRepoMockRecorder) CloseConnection() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseConnection", reflect.TypeOf((*MockIAuthorizationRepo)(nil).CloseConnection))
}

// CreateUser mocks base method.
func (m *MockIAuthorizationRepo) CreateUser(login, passwordHash string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", login, passwordHash)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockIAuthorizationRepoMockRecorder) CreateUser(login, passwordHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockIAuthorizationRepo)(nil).CreateUser), login, passwordHash)
}

// GetUser mocks base method.
func (m *MockIAuthorizationRepo) GetUser(login string) (entity.UserDAO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", login)
	ret0, _ := ret[0].(entity.UserDAO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockIAuthorizationRepoMockRecorder) GetUser(login interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockIAuthorizationRepo)(nil).GetUser), login)
}
